### ISSUE TITLE
Nexus with PostgreSQL database

### ISSUE THREAD

**Issue by michal-duma** [sonatype-nexus-community/nexus-blobstore-google-cloud#123]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
* It's a question, not an issue - I just want to know if this plugin has some limitations in the case of Nexus configuration with an external database on PostgreSQL or is just working fine. 

* **What feature or behavior is this required for?**
* (I know that configuration with PostgreSQL requires Nexus Pro version and that's fine) - I just want to know what options we have and if there are any limitations to it - so if only OrientDB is possible/supported or Nexus with PostgreSQL database will also work fine.

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by nblair** [comment]
Hi @michal-duma thanks for reaching out!

Your question is a great one, and requires a fair bit of nuance in the answer. I'm the author of this plugin, and I do work for Sonatype. This plugin was created and is maintained by me through a program for our Product and Technology employees. That program - we call it Improvement Day - affords us about 10% of our work time for self-directed activities. This allows employees to try Bold ideas, Pursue personal and professional Growth, and to do so with Transparency; we have a culture that encourages us to communicate about how we spend this time through multiple channels - demos, tech talks, blog posts, etc.

I've been actively maintaining this plugin because I enjoy to do so. It gives me a technical outlet to express my creativity. I use it for myself (single user deployment) and am aware there are deployers in the community running it successfully and that gives me great pride. My role has changed a few times in the 5 years since this plugin was first published to the community. My time available ebbs and flows. My internal deployment currently runs with OrientDB. 

**To specifically answer your question: I simply haven't tried it yet, so I don't know if it will be compatible with PostgreSQL deployments.** I have a goal to migrate my personal deployment to PostgreSQL to explore if the plugin is compatible, I hope to explore that some time this year.

Here's the business side: as a Pro customer, I am sure you are familiar with Sonatype's [Software Support Policy](https://www.sonatype.com/usage/software-support-policy). We have a high bar for what we can support. That the plugin "works" is nowhere near the minimum expectations of what it means for Sonatype to support it - our Support and Engineering teams will need the ability to create test environments, debug/diagnose, have runbooks; our Success teams will need enablement on why you would consider this plugin, the implications (performance, cost, administration), and so much more.

Since we don't have any of that in place, that's why [the fine print](https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/blame/main/README.md#L154) section on the README indicates this is not supported by Sonatype.

**If you would blend this unsupported plugin with a supported Pro licensed deployment, it puts your success at risk, as Sonatype may not be able to meet the obligations of support policy in times of crisis. If the root cause of a crisis would be related to this plugin, that would put the onus on you the deployer to remediate those risks, be it with diagnostic ability, or making local modifications to the source code, or even removing the plugin.**

Providing Pro customers with better deployment options (like Google Cloud Storage support, among others) is a candidate concept on our forward looking roadmap. There is no committed start or end date for this work at present.

I'm going to still continue to maintain - and periodically make incremental improvements - while it resides here in the community. I've always welcomed contributions and will continue to do so if you are so inclined. I hope this provides the clarity you seek!

**Comment by michal-duma** [comment]
Thank you Nicholas for such a detailed response. 
We will need to consider all the above to decide about our next steps.
For now, everything is clear and I'm closing this issue.
