### ISSUE TITLE
Current link to 0.11.0 is invalid

### ISSUE THREAD

**Issue by akettmann-e24** [sonatype-nexus-community/nexus-blobstore-google-cloud#67]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Download 11.0 version of the plugin
* **What feature or behavior is this required for?**
Use the plugin
* **How could we solve this issue? (Not knowing is okay!)**
Verify the link is valid
* **Anything else?**
Current link points to https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-blobstore-google-cloud/0.11.0/nexus-blobstore-google-cloud-0.11.0-bundle.kar

however there is no -bundle.kar file in the 0.11.0 maven directory

**Comment by nblair** [comment]
Thanks for the heads up @akettmann-e24! That's my bad, I'll get that fixed ASAP.

**Comment by akettmann-e24** [comment]
Happy to help! I guess the "bundle" version isn't needed anymore? What is the difference?

**Comment by nblair** [comment]
This is actually a side effect of some tweaks to the release process between 0.10.x and 0.11. In 34b9fc79658feb1cf8ef30050d8ae62116b7ab1a we switched the project from a single maven module to a multi-module project so that we could pick up the recommended pattern for Integration Tests with Repository Manager plugins (the test actually starts up NXRM and deploys the plugin!). The plugin is [still an OSGi bundle](https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/blob/master/nexus-blobstore-google-cloud/pom.xml#L26), the new nesting just appears to have changed the resulting filename.
